//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3634
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NppSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NppSharp.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap DefaultToolbarIcon {
            get {
                object obj = ResourceManager.GetObject("DefaultToolbarIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid dock window ID (must be greater than zero)..
        /// </summary>
        internal static string err_InvalidDockWindowId {
            get {
                return ResourceManager.GetString("err_InvalidDockWindowId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock window object is null..
        /// </summary>
        internal static string err_InvalidWindowObj {
            get {
                return ResourceManager.GetString("err_InvalidWindowObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when attempting to create an instance of a lexer object &apos;{0}&apos; in file &apos;{1}&apos;:
        ///
        ///{2}.
        /// </summary>
        internal static string err_lexer_CreateInstance {
            get {
                return ResourceManager.GetString("err_lexer_CreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when attempting to load the toolbar icon file &apos;{0}&apos;:
        ///{1}.
        /// </summary>
        internal static string err_LoadToolbarIconFile {
            get {
                return ResourceManager.GetString("err_LoadToolbarIconFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Script command data is missing..
        /// </summary>
        internal static string err_script_CmdDataMissing {
            get {
                return ResourceManager.GetString("err_script_CmdDataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when compiling script &apos;{0}&apos;:
        ///{1}.
        /// </summary>
        internal static string err_script_Compile {
            get {
                return ResourceManager.GetString("err_script_Compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when compiling scripts:
        ///{0}.
        /// </summary>
        internal static string err_script_CompileAll {
            get {
                return ResourceManager.GetString("err_script_CompileAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when attempting to create an instance of a script object &apos;{0}&apos; in file &apos;{1}&apos;:
        ///{2}.
        /// </summary>
        internal static string err_script_CreateInstance {
            get {
                return ResourceManager.GetString("err_script_CreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script directory does not exist: {0}.
        /// </summary>
        internal static string err_script_DirMissing {
            get {
                return ResourceManager.GetString("err_script_DirMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when executing the command &apos;{0}&apos;:
        ///{1}.
        /// </summary>
        internal static string err_script_Execute {
            get {
                return ResourceManager.GetString("err_script_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when loading the assembly &apos;{0}&apos;:
        ///{1}.
        /// </summary>
        internal static string err_script_LoadDll {
            get {
                return ResourceManager.GetString("err_script_LoadDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when getting the toolbar icon:
        ///{0}.
        /// </summary>
        internal static string err_ToolbarIconProperty {
            get {
                return ResourceManager.GetString("err_ToolbarIconProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugins\config\NppSharp\NppSharpDoc.chm.
        /// </summary>
        internal static string HelpFileName {
            get {
                return ResourceManager.GetString("HelpFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (default).
        /// </summary>
        internal static string OutputWindowStyleOverride {
            get {
                return ResourceManager.GetString("OutputWindowStyleOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software\NppSharp.
        /// </summary>
        internal static string Reg_Key {
            get {
                return ResourceManager.GetString("Reg_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackColor.
        /// </summary>
        internal static string Reg_OutputStyleBackColor {
            get {
                return ResourceManager.GetString("Reg_OutputStyleBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string Reg_OutputStyleBold {
            get {
                return ResourceManager.GetString("Reg_OutputStyleBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontName.
        /// </summary>
        internal static string Reg_OutputStyleFontName {
            get {
                return ResourceManager.GetString("Reg_OutputStyleFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForeColor.
        /// </summary>
        internal static string Reg_OutputStyleForeColor {
            get {
                return ResourceManager.GetString("Reg_OutputStyleForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string Reg_OutputStyleItalic {
            get {
                return ResourceManager.GetString("Reg_OutputStyleItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputWindow.
        /// </summary>
        internal static string Reg_OutputStylePrefix {
            get {
                return ResourceManager.GetString("Reg_OutputStylePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Reg_OutputStyleSize {
            get {
                return ResourceManager.GetString("Reg_OutputStyleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string Reg_OutputStyleUnderline {
            get {
                return ResourceManager.GetString("Reg_OutputStyleUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScriptDirs.
        /// </summary>
        internal static string Reg_ScriptDirs {
            get {
                return ResourceManager.GetString("Reg_ScriptDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Line {0}: error {1}: {2}.
        /// </summary>
        internal static string script_CompileError {
            get {
                return ResourceManager.GetString("script_CompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors were encountered when compiling the script &apos;{0}&apos;:.
        /// </summary>
        internal static string script_CompileErrors {
            get {
                return ResourceManager.GetString("script_CompileErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Line {0}: warning {1}: {2}.
        /// </summary>
        internal static string script_CompileWarning {
            get {
                return ResourceManager.GetString("script_CompileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings were encountered when compiling the script &apos;{0}&apos;:.
        /// </summary>
        internal static string script_CompileWarnings {
            get {
                return ResourceManager.GetString("script_CompileWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling script: {0}.
        /// </summary>
        internal static string script_Compiling {
            get {
                return ResourceManager.GetString("script_Compiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling scripts....
        /// </summary>
        internal static string script_CompilingAllScripts {
            get {
                return ResourceManager.GetString("script_CompilingAllScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading assembly: {0}.
        /// </summary>
        internal static string script_LoadingDll {
            get {
                return ResourceManager.GetString("script_LoadingDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unknown).
        /// </summary>
        internal static string script_UnknownCommand {
            get {
                return ResourceManager.GetString("script_UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugins\config\NppSharp\Scripts.
        /// </summary>
        internal static string ScriptDir {
            get {
                return ResourceManager.GetString("ScriptDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid output window font size..
        /// </summary>
        internal static string Settings_OutputSizeInvalid {
            get {
                return ResourceManager.GetString("Settings_OutputSizeInvalid", resourceCulture);
            }
        }
    }
}
