//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3634
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NppSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NppSharp.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap DefaultToolbarIcon {
            get {
                object obj = ResourceManager.GetObject("DefaultToolbarIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (default).
        /// </summary>
        internal static string OutputWindowStyleOverride {
            get {
                return ResourceManager.GetString("OutputWindowStyleOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software\NppSharp.
        /// </summary>
        internal static string Reg_Key {
            get {
                return ResourceManager.GetString("Reg_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackColor.
        /// </summary>
        internal static string Reg_OutputStyleBackColor {
            get {
                return ResourceManager.GetString("Reg_OutputStyleBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string Reg_OutputStyleBold {
            get {
                return ResourceManager.GetString("Reg_OutputStyleBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontName.
        /// </summary>
        internal static string Reg_OutputStyleFontName {
            get {
                return ResourceManager.GetString("Reg_OutputStyleFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForeColor.
        /// </summary>
        internal static string Reg_OutputStyleForeColor {
            get {
                return ResourceManager.GetString("Reg_OutputStyleForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string Reg_OutputStyleItalic {
            get {
                return ResourceManager.GetString("Reg_OutputStyleItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputWindow.
        /// </summary>
        internal static string Reg_OutputStylePrefix {
            get {
                return ResourceManager.GetString("Reg_OutputStylePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Reg_OutputStyleSize {
            get {
                return ResourceManager.GetString("Reg_OutputStyleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string Reg_OutputStyleUnderline {
            get {
                return ResourceManager.GetString("Reg_OutputStyleUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScriptDirs.
        /// </summary>
        internal static string Reg_ScriptDirs {
            get {
                return ResourceManager.GetString("Reg_ScriptDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugins\config\NppSharp.
        /// </summary>
        internal static string ScriptDir {
            get {
                return ResourceManager.GetString("ScriptDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid output window font size..
        /// </summary>
        internal static string Settings_OutputSizeInvalid {
            get {
                return ResourceManager.GetString("Settings_OutputSizeInvalid", resourceCulture);
            }
        }
    }
}
